version: '3'
services:
  app:
    container_name: app
    build: ./dev/workspace
    env_file: ./dev/workspace/env.list
    volumes:
      - ./app:/app
    ports:
      - 8081:8080
  vault:
    container_name: vault
    build: ./dev/vault
    env_file: ./dev/vault/env.list
    volumes:
      - ./dev/vault:/dev/vault
      - ./app/vault:/app/vault
    ports:
      - 8200:8200
    cap_add:
      - IPC_LOCK
